my_machine/atm/urls.py
from django.urls import path
from . import views
app_name = 'atm'
urlpatterns = [
    path('', views.index, name='login'),
    path('signup/', views.signup, name = 'signup'),
    path('<int:user_id>/main', views.main, name='main'),
    path('<int:user_id>/main/withdraw/', views.withdraw, name='withdraw'),
    path('<int:user_id>/main/deposit/', views.deposit, name='deposit'),
    path('<int:user_id>/main/statement/', views.statement, name='statement'),
]

my_machine/my_machine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('atm/', include("atm.urls")),
]

my_machine/atm/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class User(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email_id = models.CharField(max_length=20,unique=True)
    password = models.CharField(max_length=20)
    def __str__(self):
        return (self.email_id)

class transactions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    balance = models.FloatField(default=0)
    

class history(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    symbol = models.CharField(max_length=1, default="+")
    statements = models.CharField(max_length=2000)
    def __str__(self):
        return (self.statements)

my_machine/atm/views.py
# import email
from crypt import methods
from http.client import HTTPResponse
from multiprocessing import context
from pickle import GET
from re import template
import re
from urllib import request
from urllib.parse import uses_relative
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import User,transactions, history
from django.urls import reverse

def index(request):
    context = {}
    if request.method =="GET":
        # return HttpResponse("hello")
        return render(request,'atm/login.html',context)
    else:
        try:
            user = User.objects.get(email_id = request.POST["email_id"], password = request.POST["password"])
            user_id = user.id
        except User.DoesNotExist:
            return render(request,'atm/signup.html')
        return HttpResponseRedirect(reverse('atm:main', args=(user_id,)))
    


def signup(request):
    context = {}
    if request.method == 'GET':
        return render(request,'atm/signup.html',context)     
    try:
        email = User.objects.get(email_id = request.POST["email_id"])
        context = {"error":True,"first_name":request.POST['first_name'], "last_name":request.POST['last_name'], "email_id":request.POST['email_id'], "password":request.POST['password']}
        return render(request,'atm/signup.html/', context=context)


    except User.DoesNotExist:
        user_obj = User()
        user_obj.first_name = request.POST['first_name']
        user_obj.last_name = request.POST['last_name']
        user_obj.email_id = request.POST['email_id']
        user_obj.password = request.POST['password']
        user_obj.save()
        try:
            transaction_obj = transactions.objects.get(user=user_obj.id)
        except transactions.DoesNotExist:
            transaction_obj = transactions()
            transaction_obj.user = user_obj
            transaction_obj.save()
        
    # return render(request,'atm/login.html')
    return HttpResponseRedirect(reverse('atm:login'))

def main(request, user_id):
    transactions_obj = transactions.objects.get(id = user_id)
    deposit_url = f"http://127.0.0.1:8000/atm/{user_id}/main/deposit"
    withdraw_url = f"http://127.0.0.1:8000/atm/{user_id}/main/withdraw"
    statement_url = f"http://127.0.0.1:8000/atm/{user_id}/main/statement"
    context = {"transactions_obj":transactions_obj,"user_id":user_id,"deposit_url":deposit_url,"withdraw_url":withdraw_url, "statement_url":statement_url}
    # context = {"transactions_obj":transactions_obj,"user_id":user_id}
    return render(request,'atm/main.html', context)

        
    
def deposit(request, user_id):
    # return HttpResponse("Give Money pls i am poor thanks")
    if request.method == "POST":
        amount = request.POST["balance"]
        try:            
            user_obj = User.objects.get(id = user_id)
            transactions_obj = transactions.objects.get(id = user_id)
            transactions_obj.balance += float(amount)
            transactions_obj.save()
            entry = history()
            entry.user = user_obj
            entry.statements = f"Deposited {amount} rupees"
            entry.symbol = "+"
            entry.save()
            main_url = f"http://127.0.0.1:8000/atm/{user_id}/main"
            return HttpResponseRedirect(reverse('atm:main',args=(user_id,)))
        except Exception:
            context = {"error":True,"amount":amount}
            return render(request,'atm/deposit.html', context)
    else:
        return render(request, 'atm/deposit.html')
        
        
def withdraw(request, user_id):
    if request.method == "POST":
        print('------------------in POST')
        amount = request.POST["amount"]
        try:
            user_obj = User.objects.get(id=user_id)
            transaction_obj = transactions.objects.get(id=user_id)
            entry = history()
            entry.user = user_obj
            if transaction_obj.balance >= float(amount):
                transaction_obj.balance -= float(amount)
                transaction_obj.save()
            else:
                context = {"error":True}
                return render(request, 'atm/withdraw.html', context)
            entry.statements = f"Withdrew {amount} rupees"
            entry.symbol = "-"
            entry.save()
            main_url = f"http://127.0.0.1:8000/atm/{user_id}/main"
            return HttpResponseRedirect(reverse('atm:main',args=(user_id,)))
        except Exception:
            print('-------------------->>>>.qwer')
            context = {"error":True}
            return render(request, 'atm/withdraw.html', context)
    else:
        print('------------------------------>>>>')
        # return redirect('/atm/{}/main/withdraw/'.format(user_id))
        return render(request, 'atm/withdraw.html')

def statement(request, user_id):
    user_obj = User.objects.get(id=user_id)
    context = {"user":user_obj}
    return render(request, 'atm/statement.html',context)

my_machine/atm/templates/atm/deposit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if error%}
        <p style="color: red;">Enter a valid amount</p>
        <form action="{{main_url}}" method = "post">
            {% csrf_token %}
            <fieldset>
                <legend>DEPOSIT</legend>
                <label for = "balance">Deposit Amount</label>
                <input type="text" id = "balance" name="balance" value="{{amount}}">
                <button type="submit">SUBMIT</button>
            </fieldset>
        </form>
    {% else %}
        <form action="{{main_url}}" method = "post">
            {% csrf_token %}
            <fieldset>
                <legend>DEPOSIT</legend>
                <label for = "balance">Deposit Amount</label>
                <input type="text" id = "balance" name="balance">
                <button type="submit">SUBMIT</button>
            </fieldset>
        </form>
    {% endif %}
</body>
</html>

my_machine/atm/templates/atm/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'atm:login' %}" method="post">

        {% csrf_token %}
        <fieldset>
            <legend>BANK</legend>
            <label for="email_id">Email</label><br>
            <input type="text" id="email_id" name="email_id"><br>
            <label for="password">Password</label><br>
            <input type="password" id="password" name="password"><br>
        </fieldset>
        <input type="submit">
        <p>Not a Member?<a href="/atm/signup"><b>SIGNUP</b></a></p>
    </form>
</body>
</html>

my_machine/atm/templates/atm/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaction</title>
</head>
<body>
    <p>Current Balance: {{ transactions_obj.balance }}</p>
    <form action = "{{withdraw_url}}">
        <button type="submit">WITHDRAW</button>
    </form>
    <form action= "{{deposit_url}}">
        <button type="submit">DEPOSIT</button>
    </form>
    <form action="{{statement_url}}">
        <button type="submit">HISTORY</button>
    </form>
   
</body>
</html>

my_machine/atm/templates/atm/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if error%}
        <p style="color:red;">An account with this email id already exists.</p>
        <form action="/atm/signup" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>BANK</legend>
                <label for="first_name">First Name</label><br>
                <input type="text" id="first_name" name="first_name" value={{first_name}}><br>
                <label for="last_name">Last Name</label><br>
                <input type="text" id="last_name" name="last_name" value={{last_name}}><br>
                <label for="email_id">Email</label><br>
                <input type="text" id="email_id" name="email_id" value={{email_id}}><br>
                <label for="password">Password</label><br>
                <input type="password" id="password" name="password" value={{password}}><br>
            </fieldset>
            <input type="submit">
            <p>Already Member <a href="/atm/"><b>LOGIN</b></a></p>
        </form>

    {% else %}
    <form action="/atm/signup/" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>BANK</legend>
            <label for="first_name">First Name</label><br>
            <input type="text" id="first_name" name="first_name"><br>
            <label for="last_name">Last Name</label><br>
            <input type="text" id="last_name" name="last_name"><br>
            <label for="email_id">Email</label><br>
            <input type="text" id="email_id" name="email_id"><br>
            <label for="password">Password</label><br>
            <input type="password" id="password" name="password"><br>
        </fieldset>
        <input type="submit">
        <p>Already a Member?<a href="/atm/"><b>LOGIN</b></a></p>
    </form>
    {% endif %}
</body>
</html>

my_machine/atm/templates/atm/statement.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h4>History</h4>
    <ul>
        {% for statement in user.history_set.all %}
            
            {%if statement.symbol == "-"%}

                <li style="color: red;">{{ statement.statements}}</li>
            {%else%}
                <li style="color: green;">{{ statement.statements}}</li>
            {%endif%} 
            {% endfor %}
    </ul>


</body>
</html>

my_machine/atm/templates/atm/withdraw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if error%}
        <p style="color: red;">Enter a valid amount</p>
        <form action="{{main_url}}" method="post">
            {%csrf_token%}
            <fieldset>
                <legend>WITHDRAW</legend>
                <label for="amount">Withdraw Amount</label><br>
                <input type="text" id="amount" name="amount"><br>
                <button type="submit">SUBMIT</button>
            </fieldset>
        </form>
    {%else%}
        <form action="{{main_url}}" method="post">
            {%csrf_token%}
            <fieldset>
                <legend>WITHDRAW</legend>
                <label for="amount">Withdraw Amount</label><br>
                <input type="text" id="amount" name="amount"><br>
                <button type="submit">SUBMIT</button>
            </fieldset>
        </form>
    {%endif%}
</body>
</html>